name: Setup C++ toolchain

runs:
  using: "composite"

  steps:
    - shell: bash
      run: |
        set -euo pipefail
        UBUNTU_VER="$(lsb_release -rs | sed 's/\.//g')"
        wget -q "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu${UBUNTU_VER}/x86_64/cuda-keyring_1.1-1_all.deb"
        sudo dpkg -i cuda-keyring_1.1-1_all.deb

        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          build-essential \
          cmake \
          cuda-toolkit-13-2 \
          gcc \
          g++ \
          git \
          lcov \
          libcudnn9-cuda-13 \
          libcudnn9-dev-cuda-13 \
          liblapack-dev \
          libomp-dev \
          libopenblas-dev \
          ninja-build \
          pipx
        echo "/usr/local/cuda-13.2/bin" >> "$GITHUB_PATH"
        echo "LD_LIBRARY_PATH=/usr/local/cuda-13.2/lib64:${LD_LIBRARY_PATH:-}" >> "$GITHUB_ENV"

        sudo pipx ensurepath && sudo pipx install conan
        conan profile detect --force
        conan remote add conancenter https://center2.conan.io --force
        conan remote add artifactory https://conan.mrgi23.com/artifactory/api/conan/Conan-Index --force
